{% set name = "dcm2bids" %}
{% set version = "2.1.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dcm2bids-{{ version }}.tar.gz
  sha256: f1048009430a16ee49bd1a1bf8e77306947d76e13504ef602252ec44f4d1a856

build:
  number: 0
  noarch: python
  entry_points:
    - dcm2bids = dcm2bids.dcm2bids:main
    - dcm2bids_helper = dcm2bids.helper:main
    - dcm2bids_scaffold = dcm2bids:scaffold
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - future >=0.17.1
    - python >=3.5

test:
  imports:
    - dcm2bids
    - dcm2bids.scaffold
  commands:
    - pip check
    - dcm2bids --help
    - dcm2bids_helper --help
    - dcm2bids_scaffold --help
  requires:
    - pip

about:
  home: https://pypi.org/project/dcm2bids/
  summary: Reorganising NIfTI files from dcm2niix into the Brain Imaging Data Structure
  license: GPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - SamGuay
