{% set name = "dcm2bids" %}
{% set version = "3.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dcm2bids-{{ version }}.tar.gz
  sha256: 53a8a177d556df897e19d72bd517fdae0245927a8938bb9fbbd51f9f33f54f84

build:
  number: 0
  noarch: python
  entry_points:
    - dcm2bids = dcm2bids.cli.dcm2bids:main
    - dcm2bids_helper = dcm2bids.cli.dcm2bids_helper:main
    - dcm2bids_scaffold = dcm2bids.cli.dcm2bids_scaffold:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - packaging
  run:
    - python >=3.8

test:
  imports:
    - dcm2bids
  commands:
    - pip check
    - dcm2bids --help
    - dcm2bids_helper --help
    - dcm2bids_scaffold --help
  requires:
    - pip
    - packaging

about:
  home: https://pypi.org/project/dcm2bids/
  summary: Reorganising NIfTI files from dcm2niix into the Brain Imaging Data Structure
  license: GPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - SamGuay
