{% set name = "dcm2bids" %}
{% set version = "3.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dcm2bids-{{ version }}.tar.gz
  sha256: f04a6d0fea604901fc71495a91bf78f4acd9cf5d4d9af1d3b51ba47616c02407

build:
  number: 1
  noarch: python
  entry_points:
    - dcm2bids = dcm2bids.cli.dcm2bids:main
    - dcm2bids_helper = dcm2bids.cli.dcm2bids_helper:main
    - dcm2bids_scaffold = dcm2bids.cli.dcm2bids_scaffold:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - packaging
  run:
    - python >={{ python_min }}

test:
  imports:
    - dcm2bids
  commands:
    - pip check
    - dcm2bids --help
    - dcm2bids_helper --help
    - dcm2bids_scaffold --help
  requires:
    - pip
    - packaging
    - python {{ python_min }}

about:
  home: https://pypi.org/project/dcm2bids/
  summary: Reorganising NIfTI files from dcm2niix into the Brain Imaging Data Structure
  license: GPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - SamGuay
