{% set name = "dcm2bids" %}
{% set version = "3.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dcm2bids-{{ version }}.tar.gz
  sha256: ae69e273969abfd6eaadb6e33298c844eadf0482385019466e796ca0b260a3bd

build:
  number: 0
  noarch: python
  entry_points:
    - dcm2bids = dcm2bids.cli.dcm2bids:main
    - dcm2bids_helper = dcm2bids.cli.dcm2bids_helper:main
    - dcm2bids_scaffold = dcm2bids.cli.dcm2bids_scaffold:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8

test:
  imports:
    - dcm2bids
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/dcm2bids/
  summary: Reorganising NIfTI files from dcm2niix into the Brain Imaging Data Structure
  license: GPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - SamGuay
